[package]
name = "maelstrom-challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

[[bin]]
name = "kv-store"
path = "src/kv-store/main.rs"